Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2022-10, with the labels that each got.

#87 (SUP-3688) Plans to provision and import metrics
  ARCHIVES.md
  bolt-project.yaml
  files/Filesync_performance.json
  files/Postgresql_performance.json
  files/Puppetdb_performance.json
  files/Puppetserver_performance.json
  files/System_performance.json
  files/plan_files/import_archives.sh
  files/plan_files/postgres.conf
  files/plan_files/puppetdb.conf
  files/plan_files/puppetserver.conf
  files/plan_files/system_cpu.conf
  files/plan_files/system_memory.conf
  files/plan_files/system_procs.conf
  files/telegraf.conf
  manifests/profile/dashboards.pp
  plans/load_metrics.pp
  plans/provision_dashboard.pp
Labels: enhancement

#75 (SUP-3565) Support Telegraf archive install on EL
  README.md
  manifests/telegraf/agent.pp
  metadata.json
  spec/classes/agent_spec.rb
  spec/classes/init_spec.rb
Labels: enhancement

#92 Check type of $targets parameter
  plans/load_metrics.pp
Labels: bug

#91 Add file sync client metrics to archive script
  files/plan_files/puppetserver.conf
Labels: enhancement

#94 README: fix typo
  README.md
Labels: maintenance

#96 Accept a support script tarball for archive metrics ingest
  files/plan_files/import_archives.sh
  plans/load_metrics.pp
Labels: enhancement

#100 added insecure_skip_verify param
  manifests/telegraf/agent.pp
Labels: enhancement

#103 (SUP-3735) have dashboards autorefresh
  files/Filesync_performance.json
  files/Postgresql_performance.json
  files/Puppetdb_performance.json
  files/Puppetserver_performance.json
Labels: enhancement

#101 mv telegraf agent os-specific params to hiera data
  data/common.yaml
  data/os/family/Debian.yaml
  data/os/family/RedHat.yaml
  data/os/name/Ubuntu.yaml
  hiera.yaml
  manifests/telegraf/agent.pp
Labels: enhancement
