Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2022-05, with the labels that each got.

#38 (SUP-3235) Use latest telegraf package on Ubuntu
  .puppet-lint.rc
  .sync.yml
  README.md
  Rakefile
  manifests/telegraf/agent.pp
Labels: bug

#42 Add panels for PDB read and write pools
  files/Postgresql_performance.json
  files/Puppetdb_performance.json
  files/Puppetserver_performance.json
  templates/puppetdb_jvm_metrics.epp
Labels: bug, enhancement

#43 Display all http client and function metrics
  files/Puppetserver_performance.json
Labels: enhancement

#39 (SUP-3241) Add in Dashboard documentation
  README.md
Labels: enhancement

#44 Bump influxdb dependency to 1.0
  metadata.json
Labels: maintenance

#46 Add command to extract metrics archives to README
  README.md
Labels: documentation, maintenance

#47 Fix panels related to PDB connections
  files/Puppetdb_performance.json
Labels: bug

#49 Fix queue_depth metric in starlark processor
  examples/telegraf.conf.d/puppetdb.conf
Labels: bug

#50 Add panels for Puppet server GC times and counts
  files/Puppetserver_performance.json
Labels: enhancement

#51 Add PDB JVM GC panels
  examples/telegraf.conf.d/puppetdb.conf
  files/Puppetdb_performance.json
Labels: enhancement

#55 (SUP-3329) Add metric archive info to ARCHIVES.md
  ARCHIVES.md
  README.md
Labels: enhancement
