Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2022-04, with the labels that each got.

#28 Fix handling of 'error' entry in dict
  examples/telegraf.conf.d/postgres.conf
  examples/telegraf.conf.d/puppetdb.conf
Labels: bug

#32 (SUP-3201) Accept any Sensitive value in template
  files/datasource.epp
Labels: bug

#31 (SUP-3209) Grant pg_monitor role to telegraf
  manifests/profile/postgres_access.pp
Labels: bug

#25 Enable Acceptance Testing
  data/common.yaml
  data/os/Debian.yaml
  data/os/RedHat.yaml
  data/os/Suse.yaml
  spec/acceptance/init_spec.rb
  spec/fixtures/matrix/latest.json
  spec/fixtures/matrix/lts.json
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#33 (SUP-3201) Check port availability with systemd
  manifests/profile/dashboards.pp
  templates/grafana_wait.epp
Labels: bug

#35 (SUP-3228) Fix Ubuntu compatibility issue
  manifests/telegraf/agent.pp
Labels: bug

#37 make resource ordering specific to install class
  manifests/telegraf/agent.pp
Labels: bug

#36 (SUP-3061) Install class for ent infrastructure agents
  .puppet-lint.rc
  .sync.yml
  README.md
  REFERENCE.md
  functions/hosts_with_profile.pp
  manifests/enterprise_infrastructure.pp
  manifests/telegraf/agent.pp
  metadata.json
  spec/acceptance/init_spec.rb
  spec/classes/enterprise_infrastructure_spec.rb
  spec/default_facts.yml
  spec/spec_helper_acceptance_local.rb
Labels: enhancement
