Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2022-03, with the labels that each got.

#1 PDK and Cloud CI Conversion
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .fixtures.yml
  .github/workflows/pe_latest_testing.yml
  .gitlab-ci.yml
  .puppet-lint.rc
  .rubocop.yml
  .sync.yml
  .travis.yml
  CHANGELOG.md
  Gemfile
  REFERENCE.md
  Rakefile
  appveyor.yml
  functions/hosts_with_pe_profile.pp
  functions/pe_profiles_on_host.pp
  manifests/init.pp
  manifests/profile/dashboards.pp
  manifests/profile/postgres_access.pp
  manifests/telegraf/agent.pp
  manifests/telegraf/config.pp
  metadata.json
  spec/default_facts.yml
  spec/pdk.yaml
  spec/spec_helper.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#6 Bump InfluxDB dependency to 0.2.1
  metadata.json
Labels: maintenance

#9 correction of module url in metadata
  metadata.json
Labels: maintenance

#12 Remove check for toml-rb gem
  README.md
  manifests/init.pp
Labels: maintenance

#19 Fix postgres auth for Telegraf agents
  functions/hosts_with_pe_profile.pp
  functions/hosts_with_profile.pp
  manifests/init.pp
  manifests/profile/postgres_access.pp
  manifests/telegraf/agent.pp
Labels: bug

#20 Initial Acceptance Tests
  spec/acceptance/init_spec.rb
Labels: maintenance

#22 Add acceptance test fixtures
  files/matrix/latest.json
  files/matrix/lts.json
Labels: maintenance

#26 Check for existance of keys in dict
  examples/telegraf.conf.d/postgres.conf
  examples/telegraf.conf.d/puppetdb.conf
Labels: enhancement
