Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2023-10, with the labels that each got.

#193 (SUP-4478) Addition of access details for Grafana Dashboard
  README.md
Labels: documentation

#196 Update grafana 8.5.26->8.5.27
  REFERENCE.md
  manifests/profile/dashboards.pp
  spec/classes/dashboards_spec.rb
Labels: enhancement

#197 telegraf: Update Agent 1.27.0->1.28.2
  REFERENCE.md
  data/common.yaml
  manifests/telegraf/agent.pp
  spec/classes/agent_spec.rb
Labels: enhancement

#198 Cleanup puppet-strings documentation
  REFERENCE.md
  manifests/enterprise_infrastructure.pp
  manifests/init.pp
  manifests/profile/dashboards.pp
  manifests/telegraf/agent.pp
Labels: maintenance

#200 Bugfix for importing new file sync storage metrics
  files/plan_files/puppetserver.conf
Labels: bug
