Repository puppetlabs/puppet_operational_dashboards, pull requests merged in 2023-04, with the labels that each got.

#158 (SUP-3952) Remove Puppet 6 as a supported platform
  metadata.json
Labels: backwards-incompatible

#159 (SUP-4194) Puppet 8 release prep
  .pdkignore
  .rubocop.yml
  Gemfile
  Rakefile
  metadata.json
  spec/spec_helper.rb
Labels: enhancement

#162 Bump dependency for inifile
  metadata.json
Labels: maintenance

#165 Document parameters for internal repositories
  README.md
Labels: enhancement
